[package]
name = "nixism"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
confy = "0.6.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_derive = "1.0.219"
toml = "0.8.20"
